version: '3'

services:
  deluge:
    image: linuxserver/deluge:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 8112:8112
    - 58846:58846
    volumes:
    - deluge_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London

  radarr:
    image: linuxserver/radarr:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.hostname == lynette
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 7878:7878
    volumes:
    - radarr_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London

  sonarr:
    image: linuxserver/sonarr:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.hostname == lynette
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 8989:8989
    volumes:
    - sonarr_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London

volumes:
  raidz:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/user/RAIDZ"
  deluge_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/user/Docker/deluge"
  radarr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/unraid/Docker/radarr"
  sonarr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/unraid/Docker/sonarr"
