version: '3.5'

services:
  telegraf:
    image: telegraf:latest
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
    - influxdb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - telegraf_config:/etc/telegraf
    networks:
    - common

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == x86_64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    environment:
    - GF_INSTALL_PLUGINS=ntop-ntopng-datasource,grafana-piechart-panel,grafana-worldmap-panel
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_NAME=Yardnet
    networks:
    - common

  influxdb:
    image: influxdb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
        - node.platform.arch == x86_64
      resources:
        limits:
          memory: 2048M
    ports:
    - 8086:8086
    - 2003:2003
    volumes:
    - influxdb_config:/etc/influxdb
    - influxdb_data:/var/lib/influxdb
    networks:
    - common

volumes:
  telegraf_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/telegraf"
  influxdb_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/influxdb/config"
  grafana_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/grafana"
  influxdb_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/influxdb/data"

networks:
  common:
    external: true
