version: '3.5'

services:
  resilio:
    image: containrrr/watchtower
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
