apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi-poller
  namespace: kube-system
spec:
  chart: unifi-poller
  targetNamespace: unifi
  repo: https://halkeye.github.io/helm-charts
  set:
    image.tag: "stable"
  valuesContent: |-
    config:
      influxdb:
        url: "http://influx.yardnet.uk:8086"
      unifi:
        defaults:
          url: "https://unifi.yardnet.uk"
          pass: "<removed>"
          user: "<removed>"
