version: '2.1'
services:
  portainer:
    image: portainer/portainer:arm
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/RAIDZ/Docker/portainer:/data
    ports:
      - 80:9000
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - /mnt/RAIDZ/Docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /mnt/RAIDZ/Docker/influxdb/data:/var/lib/influxdb
    mem_limit: 800m
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/RAIDZ/Docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: fg2it/grafana-armhf:v5.0.4
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    links:
      - influxdb
    volumes:
      - /mnt/RAIDZ/Docker/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=ntop-ntopng-datasource,grafana-piechart-panel,grafana-worldmap-panel
  mariadb:
    image: lsioarmhf/mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /mnt/RAIDZ/Docker/mariadb:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  kodi:
    image: lsioarmhf/kodi-headless:latest
    container_name: kodi
    ports:
      - 8082:8082
      - 9777:9777/udp
      - 9090:9090
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - /mnt/RAIDZ/Docker/kodi:/config/.kodi
      - /mnt/RAIDZ:/mnt/RAIDZ
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  resilio:
    image: lsioarmhf/resilio-sync:latest
    container_name: resilio
    restart: always
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - /mnt/RAIDZ/Docker/resilio/config:/config
      - /mnt/RAIDZ/Docker/resilio/downloads:/downloads
      - /mnt/RAIDZ/Backups/Photos/Sync:/sync
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London
  transmission:
    image: lsioarmhf/transmission:latest
    container_name: transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - /mnt/RAIDZ/Docker/transmission:/config
      - /mnt/RAIDZ:/mnt/RAIDZ
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London
    networks:
      alpha:
        ipv4_address: 192.168.0.11
      default:
  couchpotato:
    image: lsioarmhf/couchpotato:latest
    container_name: couchpotato
    restart: always
    ports:
      - 5050:5050
    links:
      - transmission
    volumes:
      - /mnt/RAIDZ/Docker/couchpotato:/config
      - /mnt/RAIDZ:/mnt/RAIDZ
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London
  sickrage:
    image: lsioarmhf/sickrage:latest
    container_name: sickrage
    restart: always
    ports:
      - 8083:8081
    links:
      - transmission
    volumes:
      - /mnt/RAIDZ/Docker/sickrage:/config
      - /mnt/RAIDZ:/mnt/RAIDZ
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London
  logstash:
    build: ./logstash
    container_name: logstash
    ports:
      - 5140:5140
      - 5140:5140/udp
    volumes:
      - /mnt/RAIDZ/Docker/logstash:/etc/logstash
networks:
  alpha:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
