version: '3'
services:
  portainer:
    image: portainer/portainer:arm
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/RAIDZ/Docker/portainer:/data
    ports:
      - 80:9000
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - /mnt/RAIDZ/Docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /mnt/RAIDZ/Docker/influxdb/data:/var/lib/influxdb
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - /mnt/RAIDZ/Docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: fg2it/grafana-armhf:v5.0.4
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
     - /mnt/RAIDZ/Docker/grafana:/var/lib/grafana
  mariadb:
    image: lsioarmhf/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /mnt/RAIDZ/Docker/mariadb:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  kodi:
    image: lsioarmhf/kodi-headless:latest
    container_name: kodi
    restart: unless-stopped
    ports:
      - 8082:8080
      - 9777:9777/udp
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - /mnt/RAIDZ/Docker/kodi:/config/.kodi
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  resilio:
    image: lsioarmhf/resilio-sync:latest
    container_name: resilio
    restart: unless-stopped
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - /mnt/RAIDZ/Docker/resilio:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  unifi:
    image: lsioarmhf/unifi:latest
    container_name: unifi
    restart: unless-stopped
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    volumes:
      - /mnt/RAIDZ/Docker/unifi:/config
    environment:
      - PGID=1000
      - PUID=1000
  transmission:
    image: lsioarmhf/transmission:latest
    container_name: transmission
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - /mnt/RAIDZ/Docker/transmission:/config
      - /mnt/RAIDZ/Downloads:/mnt/RAIDZ/Downloads
      - /mnt/RAIDZ/Movies:/mnt/RAIDZ/Movies
      - /mnt/RAIDZ/TV:/mnt/RAIDZ/TV
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  couchpotato:
    image: lsioarmhf/couchpotato:latest
    container_name: couchpotato
    restart: unless-stopped
    ports:
      - 5050:5050
    volumes:
      - /mnt/RAIDZ/Docker/couchpotato:/config
      - /mnt/RAIDZ/Downloads/Movies:/mnt/RAIDZ/Downloads/Movies
      - /mnt/RAIDZ/Movies:/mnt/RAIDZ/Movies
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  sickrage:
    image: lsioarmhf/sickrage:latest
    container_name: sickrage
    restart: unless-stopped
    ports:
      - 8083:8083
    volumes:
      - /mnt/RAIDZ/Docker/sickrage:/config
      - /mnt/RAIDZ/Downloads/TV:/mnt/RAIDZ/Downloads/TV
      - /mnt/RAIDZ/TV:/mnt/RAIDZ/TV
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
