# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "charles" do |machine|
    machine.vm.box = "debian/stretch64"
    machine.vm.hostname = "charles"
    machine.vm.network 'private_network', ip: "192.168.10.80"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end

  config.vm.define "linda" do |machine|
    machine.vm.box = "debian/stretch64"
    machine.vm.hostname = "linda"
    machine.vm.network 'private_network', ip: "192.168.10.81"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    machine.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "cluster.yml"
      ansible.limit = "all"
      ansible.groups = {
        "leader" => [
          "charles"
        ],
        "members" => [
          "linda"
        ],
      }
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
      ansible.host_vars = {
        "charles" => {
          "ansible_host" => "192.168.10.80",
          "ansible_port" => 22
        },
        "linda" => {
          "ansible_host" => "192.168.10.81",
          "ansible_port" => 22
        }
      }
    end
  end

  config.ssh.insert_key = false

end
