---
- name: set up user
  include_tasks: user.yml

- name: install packages
  include_tasks: packages.yml

- name: configure networking
  include_tasks: networking.yml

- name: secure ssh
  include_tasks: ssh.yml
