---
#- name: disable armbian zram
#  lineinfile:
#    path: /etc/default/armbian-zram-config
#    line: '127.0.0.1 {{ inventory_hostname }}'

#- name: set nographics in boot.ini
#  lineinfile:
#    path: /boot/boot.ini
#    line: 'setenv nographics "1"'
