version: '3'

services:
  telegraf:
    image: telegraf:latest
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - telegraf_config:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: fg2it/grafana-armhf:v5.0.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=ntop-ntopng-datasource,grafana-piechart-panel,grafana-worldmap-panel

  logstash:
    build: logstash
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 5140:5140
      - 5140:5140/udp
    volumes:
      - logstash_data:/etc/logstash

  influxdb:
    image: influxdb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 500M
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - influxdb_config:/etc/influxdb/influxdb.conf:ro
      - influxdb_data:/var/lib/influxdb

  kodi:
    image: lsioarmhf/kodi-headless:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - mariadb
    ports:
      - 8082:8082
      - 9777:9777/udp
      - 9090:9090
    volumes:
      - kodi_data:/config/.kodi
      - raidz:/mnt/RAIDZ
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

  resilio:
    image: lsioarmhf/resilio-sync:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - resilio_data:/config
      - resilio_downloads:/downloads
      - resilio_sync:/sync
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London

  mariadb:
    image: lsioarmhf/mariadb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == manager]
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

  transmission:
    image: lsioarmhf/transmission:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - transmission_data:/config
      - raidz:/mnt/RAIDZ
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London

  couchpotato:
    image: lsioarmhf/couchpotato:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 5050:5050
    volumes:
      - couchpotato_data:/config
      - raidz:/mnt/RAIDZ
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London

  sickrage:
    image: lsioarmhf/sickrage:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
    ports:
      - 8083:8081
    volumes:
      - sickrage_data:/config
      - raidz:/mnt/RAIDZ
    environment:
      - PGID=8675309
      - PUID=8675309
      - TZ=Europe/London

volumes:
  raidz:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ"
  telegraf_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/telegraf/telegraf.conf"
  influxdb_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/influxdb/influxdb.conf"
  resilio_sync:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Backups/Photos/Sync"
  logstash_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/logstash"
  transmission_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/transmission"
  couchpotato_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/couchpotato"
  sickrage_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/sickrage"
  kodi_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/kodi"
  resilio_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,rw
      device: ":/mnt/RAIDZ/Docker/resilio/config"
  resilio_downloads:
  mariadb_data:
  influxdb_data:
  grafana_data:

