version: '3.5'

services:
  transmission:
    image: lsioarmhf/transmission:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 9091:9091
    - 51413:51413
    volumes:
    - transmission_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=8675309
    - PUID=8675309
    - TZ=Europe/London

  couchpotato:
    image: lsioarmhf/couchpotato:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 5050:5050
    volumes:
    - couchpotato_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=8675309
    - PUID=8675309
    - TZ=Europe/London
    networks:
    - common

  sickrage:
    image: threesquared/sickchill:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 8083:8081
    volumes:
    - sickrage_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=8675309
    - PUID=8675309
    - TZ=Europe/London
    networks:
    - common

volumes:
  raidz:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ"
  transmission_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/transmission"
  couchpotato_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/couchpotato"
  sickrage_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/sickrage"

networks:
  common:
    external: true
