version: '3'

services:
  transmission:
    image: linuxserver/transmission:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 9091:9091
    - 53725:53725
    volumes:
    - transmission_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=8675309
    - PUID=8675309
    - TZ=Europe/London

  radarr:
    image: linuxserver/radarr:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 7878:7878
    volumes:
    - radarr_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PUID=8675309
    - PGID=8675309
    - TZ=Europe/London

  sonarr:
    image: linuxserver/sonarr:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 8989:8989
    volumes:
    - sonarr_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PUID=8675309
    - PGID=8675309
    - TZ=Europe/London

  couchpotato:
    image: linuxserver/couchpotato:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 5050:5050
    volumes:
    - couchpotato_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=8675309
    - PUID=8675309
    - TZ=Europe/London

  sickrage:
    image: linuxserver/sickchill:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
    - 8083:8081
    volumes:
    - sickrage_data:/config
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=8675309
    - PUID=8675309
    - TZ=Europe/London

volumes:
  raidz:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ"
  transmission_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/transmission"
  couchpotato_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/couchpotato"
  sickrage_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/sickrage"
  radarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/radarr"
  sonarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/sonarr"
