version: '3.5'

services:
  kodi:
    image: linuxserver/kodi-headless:latest
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.platform.arch == aarch64
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
    - mariadb
    ports:
    - 8082:8080
    - 9777:9777/udp
    - 9090:9090
    volumes:
    - kodi_data:/config/.kodi
    - raidz:/mnt/RAIDZ
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    networks:
    - common

  mariadb:
    image: linuxserver/mariadb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
        - node.platform.arch == x86_64
    ports:
    - 3306:3306
    volumes:
    - mariadb_data:/config
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    networks:
    - common

volumes:
  raidz:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ"
  kodi_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.3,nolock,soft,rw
      device: ":/mnt/RAIDZ/Docker/kodi"
  mariadb_data:

networks:
  common:
    external: true
