apiVersion: v1
kind: Namespace
metadata:
  name: unifi

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: unifi
  repo: https://k8s-at-home.com/charts/
  targetNamespace: unifi
  set:
    image.tag: "latest"
  valuesContent: |-
    persistence:
      enabled: true
      storageClass: "nfs-client"
    mongodb:
      enabled: true
      dbUri: mongodb://mongo.yardnet.uk/unifi
      statDbUri: mongodb://mongo.yardnet.uk/unifi_stat
    ingress:
      enabled: true
      hosts:
        - "unifi.yardnet.uk"
