# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "cult-leader", primary: true do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cult-leader"
    machine.vm.network 'private_network', ip: "192.168.10.80"
  end

  config.vm.define "cult-member-1" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "cult-member-1"
    machine.vm.network 'private_network', ip: "192.168.10.81"
  end

  config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "cluster.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
    ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end
