# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "charles.cult.mansyard.uk" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "charles.cult.mansyard.uk"
    machine.vm.network 'private_network', ip: "192.168.10.80"
  end

  config.vm.define "linda.cult.mansyard.uk" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "linda.cult.mansyard.uk"
    machine.vm.network 'private_network', ip: "192.168.10.81"

    machine.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "cluster.yml"
      ansible.inventory_path = "inventory"
      ansible.limit = "all"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
    end
  end

  config.ssh.insert_key = false

end
