---
- name: create swarm as manager
  shell: docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}
  when: "docker_info.stdout.find('Swarm: inactive') != -1"

- name: get swarm worker token
  shell: docker swarm join-token -q worker
  register: worker_token

- name: clone config files
  git:
    repo: ssh://git@github.com/threesquared/homelab.git
    dest: /home/{{ username }}/homelab
  become_user: "{{ username }}"

- name: apply portainer configs
  docker_stack:
    state: present
    name: portainer
    compose:
      - /home/{{ username }}/homelab/cult/docker/swarm/portainer.yml
